import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";
import {
  Student,
  Company,
  School,
  Internship,
  Supervisor,
  Advisor,
} from "@/types/database";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", lineHeight: 1.5 },
  header: {
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "bold",
    textDecoration: "underline",
  },
  section: { marginBottom: 15 },
  title: {
    fontWeight: "bold",
    marginBottom: 5,
    backgroundColor: "#f0f0f0",
    padding: 3,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
    paddingVertical: 3,
  },
  label: { width: 120, fontWeight: "bold" },
  content: { flex: 1 },
  footer: {
    marginTop: 50,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  signature: {
    borderTopWidth: 1,
    borderTopColor: "#000",
    width: 180,
    textAlign: "center",
    paddingTop: 5,
  },
});

interface TREProps {
  data: {
    student: Student;
    company: Company;
    school: School;
    internship: Internship;
    supervisor: Supervisor;
    advisor: Advisor;
  };
}

export const TRETemplate = ({ data }: TREProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text>INTERNSHIP COMPLETION TERM (TRE)</Text>
      </View>

      <View style={styles.section}>
        <Text>
          The company {data.company?.business_name}, registered under CNPJ No.{" "}
          {data.company?.cnpj}, declares for all due purposes that the student{" "}
          {data.student?.name}, holder of CPF {data.student?.cpf}, has completed
          the Supervised Curricular Internship at this organization.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.title}>PERIOD SUMMARY</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Start:</Text>
          <Text style={styles.content}>
            {new Date(data.internship?.start_date).toLocaleDateString("en-US")}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>End:</Text>
          <Text style={styles.content}>
            {new Date(data.internship?.end_date).toLocaleDateString("en-US")}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Workload:</Text>
          <Text style={styles.content}>
            {data.internship?.total_workload} total hours
          </Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.title}>FINAL EVALUATION</Text>
        <Text>
          The intern satisfactorily fulfilled the activities provided for in
          their Activity Plan, demonstrating technical competence and
          professional commitment throughout the entire period of practical
          experience.
        </Text>
      </View>

      <View style={styles.footer}>
        <View style={styles.signature}>
          <Text>Company Representative</Text>
        </View>
        <View style={styles.signature}>
          <Text>Internship Coordinator</Text>
        </View>
      </View>

      <Text
        style={{
          marginTop: 20,
          textAlign: "center",
          fontSize: 8,
          color: "#666",
        }}
      >
        Automatically generated by SEGECS on{" "}
        {new Date().toLocaleDateString("en-US")}
      </Text>
    </Page>
  </Document>
);
